---
spring:
  #连接数据库，驱动，用户名，密码，url路径
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: gu784341
    url: jdbc:mysql://127.0.0.1:3306/springboot?serverTimezone=Asia/Shanghai
    schema: classpath:sql/*.sql
    initialization-mode: always
  #建表SQL文件地址
#mybatis 配置
mybatis:
  #数据访问dao映射实现方法
  #实体类所在的包路径
  type-aliases-package: com.example.jdktest.entity
  mapper-locations: classpath:mapper/*.xml
---

